export const bestRestaurants = {
  img: "",
  title: "Discover the best restaurants near you",
  sub_title: "Over 17,000 restaurants in 12 countries. Find and reserve the very best of them in your neighbourhood, your city and beyond.",
  button: "Discover restaurants",
  data: [
    {
      id: 1,
      status: "NEW",
      title: "Yoon's Social Kitchen by Yoon's Traditional Teochew Kueh",
      img: "https://qul.imgix.net/770572a5-73da-49a4-ae7e-1f9df05362b8/608231_sld.jpg?auto=format&w=1024",
      range: "MacPherson",
      location: "Chinese",
      price: 2,
      rate: 5.7,
    },
    {
      id: 2,
      status: "NEW",
      title: "Latteria Mozzarella Bar",
      img: "https://qul.imgix.net/870db6b8-a6fd-4ab1-a34e-67d618b3f688/585374_sld.jpg?auto=format&w=1024",
      range: "Duxton",
      location: "Italian",
      price: 3,
      rate: 5.2,
      comment: "1070 reviews",
    },
    {
      id: 3,
      status: "OLD",
      title: "The Grumpy Bear - Thomson Plaza",
      img: "https://qul.imgix.net/bb79785f-ea10-489a-90a4-88d9c28871aa/606890_sld.jpg?auto=format&w=1024",
      range: "Upper Thomson",
      location: "Western",
      price: 2,
      rate: 4.7,
      comment: "9 reviews",
    },
  ],
}