export const dataFooter = [
  {
    title: "LEGAL",
        sub_title1: "Imprint",
        sub_title2: "Privacy Policy", 
        sub_title3: "Term and Conditions",
  },
  {
    title: "ABOUT",
    sub_title1: "Loyalty Points",
    sub_title2: "Quisine Blog",
    sub_title3: "Contact",
    sub_title4: "List your restaurant",
    sub_title5: "Careers",
    sub_title6: "Press",
    sub_title7: "Sitemap",
  },
  {
    title: "COUNTRIES AND REGIONS",
    sub_title1:     "Australia",
    img: "../../public/images/australia.png",
    sub_title2:     "New Zealand",
    sub_title3:     "Austria",
    sub_title4:     "Switzerland",
    sub_title5:     "Germany",
    sub_title6:     "Italy",
    sub_title7:     "Finland",
    sub_title8:     "United Kingdom",
    sub_title9:     "Luxembourg",
    sub_title10:    "Turkey",
    sub_title11:    "Netherlands",
    sub_title12:    "Singapore",
    sub_title13:    "Hong Kong",
  }
];
