export const topDistricts = {
  title1: "Top districts for restaurants",
  title2: "Top cities for restaurants",
  title3: "Top points for interrest",
  data1: [
    "Bugis, Singapore",
    "Tanjong Pagar, Singapore",
    "Orchard, Singapore",
    "Raffles Place, Singapore",
    "Chinatown, Singapore",
    "City Hall, Singapore",
    "Boat Quay, Singapore",
    "Bukit Timah, Singapore",
    "Telok Ayer, Singapore",
    "Somerset, Singapore",
    "Jurong East, Singapore",
    "Clarke Quay, Singapore",
    "Farrer Park, Singapore",
    "Esplanade, Singapore",
    "Robertson Quay, Singapore",
  ],
  data2: ["Restaurants in Singapore"],
  data3: [
    "Bugis Plus, Singapore",
    "Chijmes, Singapore",
    "Duo Residences, Singapore",
    "Goodman Arts Centre, Singapore",
    "Haji Lane, Singapore",
    "Kwan Im Thong Hood Cho Temple, Singapore",
    "Masjid Sultan, Singapore",
    "National Library, Singapore",
    "Parco Bugis Junction, Singapore",
    "Sri Krishnan Temple, Singapore",
  ],
};

