import Districts from '@/components/Districts';
import RestaurantGuide from '@/components/RestaurantGuide';
import SildeFind from '@/components/SlideFind';
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quandoo Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SildeFind/>
      <RestaurantGuide />
      <Districts/>
    </div>
  );
}

export default Home
